/**
 * lib/demo-data-blocks.ts — the itinerary the prototype opens on.
 *
 * Split out of demo-data.ts only because twenty blocks with their reasons is a
 * lot of prose; everything here is re-exported from demo-data.ts, which is the
 * file the screens import.
 *
 * Every block carries all three `reason` lines and, where the retrieval layer
 * actually holds something about the place, a `sourceCitation`. That is the
 * product's first principle — every block explains itself — so a block with an
 * empty reason would be a bug, not a shortcut.
 */

import { MOCK_CHUNKS } from './__mocks__/knowledge';
import type { Block, SourceCitation } from './schemas';

/**
 * Pull one of the chunks the retrieval layer actually returns.
 *
 * Looked up by a marker rather than copied, so the demo cannot drift away from
 * what the corpus holds. A miss throws at import: a citation naming a source
 * nobody retrieved is the exact failure this product exists to prevent.
 */
function cite(marker: string): SourceCitation {
  const chunk = MOCK_CHUNKS.find((c) => c.chunk.includes(marker));
  if (!chunk) throw new Error(`demo-data: no retrieved chunk matches "${marker}"`);
  return { text: chunk.chunk, source: chunk.source, url: chunk.url ?? null };
}

const T = 'demo-trip-osaka';

export const DEMO_BLOCKS: Block[] = [
  // ---- Day 1 · Mon 7 Sep — the castle side ---------------------------------
  {
    id: 'b01',
    tripId: T,
    day: 1,
    startTime: '09:30',
    durationMin: 120,
    title: 'Osaka Castle and Nishinomaru Garden',
    subtitle: 'Chuo · keep and grounds',
    placeId: 'osaka-castle',
    costPerPerson: 55,
    locked: false,
    reason: {
      budget: 'RM 55 of day one’s RM 300 — the grounds are free, only the keep is ticketed.',
      votes: '3 👍 / 0 👎 · Wei’s must-do',
      constraint: 'Opens 09:00; the first slot clears the tour-bus queues.',
    },
    sourceCitation: cite('public park'),
    createdBy: 'ai',
  },
  {
    id: 'b02',
    tripId: T,
    day: 1,
    startTime: '12:00',
    durationMin: 60,
    title: 'Lunch at Miraiza Osaka-jo',
    subtitle: 'Inside the castle park',
    placeId: 'miraiza-osakajo',
    costPerPerson: 75,
    locked: false,
    reason: {
      budget: 'RM 75 — the priciest lunch of the trip, and the only one inside a sight.',
      votes: '2 👍 / 1 👎 · Amirah flagged the price',
      constraint: 'Amirah is vegetarian → the hall has a meat-free counter.',
    },
    sourceCitation: null,
    createdBy: 'ai',
  },
  {
    id: 'b03',
    tripId: T,
    day: 1,
    startTime: '14:00',
    durationMin: 120,
    title: 'Osaka Museum of History',
    subtitle: 'Across the moat · 10th-floor view back at the keep',
    placeId: 'osaka-museum-history',
    costPerPerson: 40,
    locked: false,
    reason: {
      budget: 'RM 40 · two of you qualify for the student rate.',
      votes: '2 👍 / 0 👎 · Amirah’s museums, Wei’s history',
      constraint: 'Closed Tuesdays, so it is today or nothing.',
    },
    sourceCitation: null,
    createdBy: 'ai',
  },
  {
    id: 'b04',
    tripId: T,
    day: 1,
    startTime: '18:00',
    durationMin: 120,
    title: 'Dinner in Dotonbori',
    subtitle: 'Canal side · Jia’s table is booked',
    placeId: 'dotonbori',
    costPerPerson: 130,
    locked: true,
    reason: {
      budget: 'RM 130 — the table is prepaid, so this number cannot move.',
      votes: '4 👍 / 0 👎 · Jia’s must-do',
      constraint: 'Jia does not eat pork → the booking is at a seafood counter.',
    },
    sourceCitation: cite('busiest after dark'),
    createdBy: 'captain',
  },

  // ---- Day 2 · Tue 8 Sep — the bay -----------------------------------------
  {
    id: 'b05',
    tripId: T,
    day: 2,
    startTime: '09:30',
    durationMin: 150,
    title: 'Osaka Aquarium Kaiyukan',
    subtitle: 'Bay · the whale shark tank',
    placeId: 'kaiyukan',
    costPerPerson: 130,
    locked: false,
    reason: {
      budget: 'RM 130 · the biggest single ticket outside USJ.',
      votes: '3 👍 / 1 👎',
      constraint: 'Opens 09:30 — being there at open buys an hour before the school groups.',
    },
    sourceCitation: cite('Chuo subway line'),
    createdBy: 'ai',
  },
  {
    id: 'b06',
    tripId: T,
    day: 2,
    startTime: '12:30',
    durationMin: 60,
    title: 'Lunch at Tempozan Marketplace',
    subtitle: 'Two minutes from the aquarium door',
    placeId: 'tempozan-marketplace',
    costPerPerson: 70,
    locked: false,
    reason: {
      budget: 'RM 70 · food-court pricing, not restaurant pricing.',
      votes: '2 👍 / 0 👎',
      constraint: 'The only bay option with both vegetarian and halal stalls.',
    },
    sourceCitation: null,
    createdBy: 'ai',
  },
  {
    id: 'b07',
    tripId: T,
    day: 2,
    startTime: '14:30',
    durationMin: 60,
    title: 'Tempozan Giant Ferris Wheel',
    subtitle: 'Bay · one 15-minute rotation',
    placeId: 'tempozan-ferris-wheel',
    costPerPerson: 40,
    locked: false,
    reason: {
      budget: 'RM 40 · the cheapest view in the city.',
      votes: '2 👍 / 1 👎 · Sarah wants views',
      constraint: 'Enclosed gondolas, so weather does not cancel it.',
    },
    sourceCitation: null,
    createdBy: 'ai',
  },
  {
    id: 'b08',
    tripId: T,
    day: 2,
    startTime: '18:00',
    durationMin: 120,
    title: 'Dinner at Namba Sennichimae',
    subtitle: 'Arcade backstreets, two streets south of the crowds',
    placeId: 'namba-sennichimae',
    costPerPerson: 140,
    locked: true,
    reason: {
      budget: 'RM 140 · inside the evening allowance with RM 20 spare.',
      votes: '4 👍 / 0 👎 · the only unanimous block on the plan',
      constraint: 'Amirah is vegetarian and Jia avoids pork — this street clears both. Locked by Wei.',
    },
    sourceCitation: cite('vegetarian and halal scene'),
    createdBy: 'ai',
  },

  // ---- Day 3 · Wed 9 Sep — Universal ---------------------------------------
  {
    id: 'b09',
    tripId: T,
    day: 3,
    startTime: '09:00',
    durationMin: 300,
    title: 'Universal Studios Japan',
    subtitle: 'Konohana · dated tickets, already paid',
    placeId: 'usj',
    costPerPerson: 420,
    locked: true,
    reason: {
      budget: 'RM 420 · 22% of the whole trip, and non-refundable.',
      votes: '3 👍 / 1 👎 · Sarah’s must-do',
      constraint: 'The tickets are date-locked to today. Nothing may move this.',
    },
    sourceCitation: cite('same-day re-entry'),
    createdBy: 'captain',
  },
  {
    id: 'b10',
    tripId: T,
    day: 3,
    startTime: '14:30',
    durationMin: 60,
    title: 'Lunch at Universal CityWalk',
    subtitle: 'Outside the gates · re-entry allowed',
    placeId: 'universal-citywalk',
    costPerPerson: 85,
    locked: false,
    reason: {
      budget: 'RM 85 outside the park against about RM 140 inside it.',
      votes: '3 👍 / 0 👎',
      constraint: 'Same-day re-entry is what makes leaving for lunch free.',
    },
    sourceCitation: null,
    createdBy: 'ai',
  },
  {
    id: 'b11',
    tripId: T,
    day: 3,
    startTime: '16:00',
    durationMin: 180,
    title: 'Universal Studios Japan, evening run',
    subtitle: 'Back in on the same ticket',
    placeId: 'usj',
    costPerPerson: 0,
    locked: false,
    reason: {
      budget: 'RM 0 · already covered by the morning ticket.',
      votes: '3 👍 / 1 👎',
      constraint: 'Queues drop after 16:00 and the park runs to 21:00.',
    },
    sourceCitation: null,
    createdBy: 'ai',
  },
  {
    id: 'b12',
    tripId: T,
    day: 3,
    startTime: '20:00',
    durationMin: 90,
    title: 'Late dinner at Umeda Food Hall',
    subtitle: 'Kita · on the way back from the park',
    placeId: 'umeda-food-hall',
    costPerPerson: 120,
    locked: false,
    reason: {
      budget: 'RM 120 · the most expendable meal on the plan.',
      votes: '2 👍 / 1 👎',
      constraint: 'Open to 23:00, which is the only reason it fits after a park day.',
    },
    sourceCitation: null,
    createdBy: 'ai',
  },

  // ---- Day 4 · Thu 10 Sep — Kita -------------------------------------------
  {
    id: 'b13',
    tripId: T,
    day: 4,
    startTime: '09:30',
    durationMin: 90,
    title: 'Umeda Sky Building',
    subtitle: 'Kita · the floating garden observatory',
    placeId: 'umeda-sky-building',
    costPerPerson: 90,
    locked: false,
    reason: {
      budget: 'RM 90 · Sarah’s second view, and the last one on the plan.',
      votes: '3 👍 / 0 👎 · Sarah wants views',
      constraint: 'Indoors above the escalator, so weather does not decide it.',
    },
    sourceCitation: null,
    createdBy: 'ai',
  },
  {
    id: 'b14',
    tripId: T,
    day: 4,
    startTime: '11:30',
    durationMin: 90,
    title: 'Nakanoshima Park riverside walk',
    subtitle: 'Kita · the rose garden end',
    placeId: 'nakanoshima-park',
    costPerPerson: 0,
    locked: false,
    reason: {
      budget: 'RM 0 · a free block was needed after the RM 420 day.',
      votes: '2 👍 / 0 👎 · Amirah’s parks',
      constraint: 'Amirah asked for a chill pace; this is the slowest hour of the trip.',
    },
    sourceCitation: null,
    createdBy: 'ai',
  },
  {
    id: 'b15',
    tripId: T,
    day: 4,
    startTime: '14:00',
    durationMin: 120,
    title: 'National Museum of Art, Osaka',
    subtitle: 'Kita · the underground galleries',
    placeId: 'nmao',
    costPerPerson: 55,
    locked: false,
    reason: {
      budget: 'RM 55 · permanent collection only.',
      votes: '2 👍 / 1 👎 · Amirah’s museums',
      constraint: 'Closed Mondays, so day 4 is the only clean slot.',
    },
    sourceCitation: null,
    createdBy: 'ai',
  },
  {
    id: 'b16',
    tripId: T,
    day: 4,
    startTime: '18:00',
    durationMin: 90,
    title: 'Dinner at Tenjinbashisuji Shotengai',
    subtitle: 'Kita · 2.6 km of covered arcade',
    placeId: 'tenjinbashisuji',
    costPerPerson: 110,
    locked: false,
    reason: {
      budget: 'RM 110 · arcade prices, and the cheapest sit-down left on the plan.',
      votes: '3 👍 / 0 👎 · Jia’s street food',
      constraint: 'Covered end to end, so rain never cancels it.',
    },
    sourceCitation: cite('longest covered shopping street'),
    createdBy: 'ai',
  },

  // ---- Day 5 · Fri 11 Sep — Tennoji ----------------------------------------
  {
    id: 'b17',
    tripId: T,
    day: 5,
    startTime: '09:30',
    durationMin: 90,
    title: 'Shitennoji Temple',
    subtitle: 'Tennoji · Japan’s oldest state temple',
    placeId: 'shitennoji',
    costPerPerson: 30,
    locked: false,
    reason: {
      budget: 'RM 30 · the grounds are free, the inner garden is ticketed.',
      votes: '2 👍 / 0 👎 · Wei’s history',
      constraint: 'Last entry 16:30 — a morning block or nothing.',
    },
    sourceCitation: null,
    createdBy: 'ai',
  },
  {
    id: 'b18',
    tripId: T,
    day: 5,
    startTime: '11:30',
    durationMin: 90,
    title: 'Tennoji Park and Keitakuen Garden',
    subtitle: 'Tennoji · ten minutes on foot from the temple',
    placeId: 'tennoji-park',
    costPerPerson: 15,
    locked: false,
    reason: {
      budget: 'RM 15 · the garden ticket, nothing else.',
      votes: '2 👍 / 1 👎 · Amirah’s parks',
      constraint: 'Open air the whole way — the first thing rain takes out.',
    },
    sourceCitation: null,
    createdBy: 'ai',
  },
  {
    id: 'b19',
    tripId: T,
    day: 5,
    startTime: '14:00',
    durationMin: 90,
    title: 'Abeno Harukas observatory',
    subtitle: 'Tennoji · 300 m, the tallest in Japan',
    placeId: 'abeno-harukas',
    costPerPerson: 95,
    locked: false,
    reason: {
      budget: 'RM 95 · the last discretionary ticket on the plan.',
      votes: '2 👍 / 2 👎 · the closest thing to a split vote',
      constraint: 'Indoors and open to 22:00, so it can move almost anywhere.',
    },
    sourceCitation: null,
    createdBy: 'ai',
  },
  {
    id: 'b20',
    tripId: T,
    day: 5,
    startTime: '18:00',
    durationMin: 120,
    title: 'Farewell dinner in Dotonbori',
    subtitle: 'Canal side · the table is held',
    placeId: 'dotonbori',
    costPerPerson: 180,
    locked: true,
    reason: {
      budget: 'RM 180 · the one deliberate splurge, agreed up front.',
      votes: '4 👍 / 0 👎',
      constraint: 'Booked and confirmed for the last night. Locked by Wei.',
    },
    sourceCitation: cite('busiest after dark'),
    createdBy: 'captain',
  },
];
